config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'allevents' => 'events#all'
  post '/invite' => 'users#invite'
  resources :users
  resources :events,    only: [:create,:new, :destroy, :show]

end

app/models/event.rb
class Event < ActiveRecord::Base
	today = Time.now.to_date
  #scope :upcoming, ->{ where("date_of == #{today}")}
  scope :upcoming, ->{ where("date_of >= ?", Time.now.to_date) } 
  scope :past, ->{ where("date_of < ?", Time.now.to_date) }
  
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations
  #validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 140 }
  validates :date_of, presence: true
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :attendee, class_name: 'User'
	belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			format: { with: VALID_EMAIL_REGEX },
			uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	has_many :created_events, dependent: :destroy, class_name: 'Event', foreign_key: :creator_id
	has_many :invitations, foreign_key: :attendee_id
	has_many :attended_events, through: :invitations

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
		@event = Event.new
	end

	def show
		@event = Event.find(params[:id])
		@uninvited = User.all - @event.attendees
		
	end

	def all
		@Uevents = current_user.created_events.upcoming
		@Pevents = current_user.created_events.past
	end

	def create
		#@event = current_user.events.create(event_params)
		@event = current_user.created_events.create(event_params)
		if @event.save
			redirect_to root_url
		else
			render 'new'
		end
	end

	private

	def event_params
		params.require(:event).permit(:title, :description, :date_of)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_url
    end
  end

  def create
    if logged_in?
      redirect_to root_url
    else
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email or password combination'
  		render 'new'
  	end
  end	
  end


  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		@events = Event.upcoming
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def index
    @users = User.all
  end

  def invite
    user_to_invite = User.find(params[:info][:user_id])
    event_to_invite_to = Event.find(params[:info][:event_id])
    user_to_invite.attended_events << event_to_invite_to
    redirect_to event_to_invite_to
  end

  def show
    @user = User.find(params[:id])
    @events = @user.created_events
    @Aevents = @user.attended_events
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
      remember @user
  		flash[:success] = "Welcome to the sample app"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
		
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li id="micropost-<%= event.id %>" >

<span class="content"><%= link_to event.title, event %></span>
<span class="timestamp"> <%= event.date_of %></span>

<!-- <span class="content"><%= link_to "Invite people","#" %></span> -->

</li> 

app/views/events/all.html.erb
<ol><h2>My Upcoming Events</h2>
<% if @Uevents.any?  %>
	<%= render @Uevents %>
<% else %>
	<p class="faint">Sorry, you don't have any upcoming events</p>
<% end  %>
<hr>
<h2>My Past Events</h2>
<% if @Pevents.any? %>
	<%= render @Pevents %>
<% else %>
	<p class="faint">Sorry, you don't have any past events</p>
<% end %>

</ol>

app/views/events/new.html.erb
<h1>Create Event</h1>


<%= current_user.name %>
<%= form_for @event do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
 

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :date_of %>
  <%= f.date_select :date_of %>
  
  <%= f.submit  %>
<% end %>

app/views/events/show.html.erb
<h1>Event Information</h1>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info" >

			<%= image_tag "feteam.png" %>
			<h4> Title:<%= @event.title %> </h4>
			<h4> Date: <%= @event.date_of %></h4>
			<h4><%= link_to "who created the event?", @event.creator %></h4>
			<p>Description: <%= @event.description %></p>
			<h2>Invite people</h2>
			
			<% @uninvited.each do |user| %>
			<h3><%= user.name %></h3>
			<span class="float:right"><%= link_to "Invite",invite_path(info: {user_id: user.id, event_id: @event.id}), method: :post %></span>
			<% end %>

		</section>
	</aside>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	<div class="col-md-6">
		<%= link_to root_url  do %>
			<%= image_tag "marker.png", class: "logo" %>
		<% end %>
		</div>
		<div class="col-md-6">
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "HOME", root_path %> </li>
				<% if logged_in? %>
                <li><%= link_to "My Events", allevents_path %></li>
          			
                <li><%= link_to "Create Event", new_event_path %></li>
          			<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
			</ul>
		</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	
	<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
	
<div class="center jumbotron">
	<h1> Welcome to Private Events</h1>
	
	<% if logged_in? %>

	<% else %>
	<span> Sign Up or Login to join events </span><br>
	<%= link_to "SignUp", signup_path, class: "btn btn-lg btn-primary" %>
	<% end %>
</div>
<br>
	
	<div class="col-lg-12 ">
	<h3 class="center">Following are the Upcoming/Todays Events, please signup to get invitation </h3>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>Title</th>
					<th>Description</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
			<% @events.each do |event| %>
				<tr>
					<td><%= link_to event.title, event %></td>
					<td><%= event.description %></td>

					<td><%= event.date_of %></td>
					
				</tr>
				<% end %>
			</tbody>
		
		</table>
	</div>
	</div>
	
	
	
	

app/views/users/_user.html.erb
 <li>
      
      <%= link_to user.name, user %>
      
    | <%= link_to "invite", invite_path(info: {user_id: user.id,event_id: @event.id}), method: :post  %>
  		
    </li>

app/views/users/index.html.erb
<h1> Send Invitation to Following users</h1>
<%# will_paginate %>
<ul>
	<%= render @users %>
</ul>
<%# will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		<!-- render a error file here -->
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>

		<%= f.label :email %>
		<%= f.text_field :email, class: 'form-control' %>
 
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.submit "Create Account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_info" >
			<h1><%= @user.name %></h1>
		</section>
	</aside>
	</div>
	<div class="row">
	<div class="col-md-8">
		<ol class="microposts">
		<h1>My Created Events</h1>
		
		<% if @user.created_events.any? %>
			<%= render @user.created_events %>
			<% else %>
			<p>Sorry You have not created any event</p>
			<% end %>
		</ol>
		<ol class="microposts">
		<h1>Invitation for Events</h1>

			<% if @user.attended_events.any?  %>
			<%= render @user.attended_events %>
			<% else %>
			<p>Sorry no attended events</p>
			<% end %>
		</ol>
	</div>
</div>